# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - ECR_REPO=679404489841.dkr.ecr.us-east-1.amazonaws.com/deploy-ecs-multi-env

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - shippable_retry npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker build -t $ECR_REPO:$BRANCH.$BUILD_NUMBER .; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker push $ECR_REPO:$BRANCH.$BUILD_NUMBER ; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then echo "versionName=$BRANCH.$BUILD_NUMBER" > $JOB_STATE/deploy-ecs-multi-env-image.env ; fi'

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  # adding awsKeys integration so that credentials are available to CI Job
  # http://docs.shippable.com/platform/integration/aws-keys/
  hub:
    - integrationName: dr-aws-keys
      type: amazonKeys


resources:

  ######################################
  # The image containing the application
  ######################################

  - name: deploy-ecs-multi-env-image
    type: image
    flags:
      - deploy-ecs-multi-env
    integration: dr-aws-keys
    pointer:
      sourceName: "679404489841.dkr.ecr.us-east-1.amazonaws.com/deploy-ecs-multi-env"
    seed:
      versionName: "latest"


  ############################
  # cluster for parallel envs
  ############################

  - name: deploy-ecs-multi-env-maincluster
    type: cluster
    flags:
      - deploy-ecs-multi-env
    integration: dr-aws-keys
    pointer:
      sourceName : "deploy-ecs-basic" #name of the cluster to which we are deploying
      region: "us-east-1"

  ###########################
  # clusters for serial envs
  ###########################

  - name: deploy-ecs-multi-env-betacluster
    type: cluster
    flags:
      - deploy-ecs-multi-env
    integration: dr-aws-keys
    pointer:
      sourceName : "deploy-ecs-basic" #name of the cluster to which we are deploying
      region: "us-east-1"

  - name: deploy-ecs-multi-env-prodcluster
    type: cluster
    flags:
      - deploy-ecs-multi-env
    integration: dr-aws-keys
    pointer:
      sourceName : "deploy-ecs-basic" #name of the cluster to which we are deploying
      region: "us-east-1"


  ####################################
  # Advanced options for multiple envs
  ####################################

  - name: deploy-ecs-multi-env-commonparams
    type: params
    version:
      params:
        SLACK_TOKEN: "abc123"

  - name: deploy-ecs-multi-env-prodopts
    type: dockerOptions
    flags:
      - deploy-ecs-multi-env
    version:
      memory: 512

  - name: deploy-ecs-multi-env-betaopts
    type: dockerOptions
    flags:
      - deploy-ecs-multi-env
    version:
      memory: 128

  - name: deploy-ecs-multi-env-blueparams
    type: params
    flags:
      - deploy-ecs-multi-env
    version:
      params:
        ENVIRONMENT: "blue"

  - name: deploy-ecs-multi-env-greenparams
    type: params
    flags:
      - deploy-ecs-multi-env
    version:
      params:
        ENVIRONMENT: "green"


  - name: deploy-ecs-multi-env-betaparams
    type: params
    flags:
      - deploy-ecs-multi-env
    version:
      params:
        ENVIRONMENT: "beta"
        SLACK_CHANNEL: "beta"

  - name: deploy-ecs-multi-env-prodparams
    type: params
    flags:
      - deploy-ecs-multi-env
    version:
      params:
        ENVIRONMENT: "prod"
        SLACK_CHANNEL: "prod"


jobs:

  ###################################
  # runCI job to update the image tag
  ###################################
  - name: deploy-ecs-multi-env_runCI
    type: runCI
    flags:
      - deploy-ecs-multi-env
    steps:
      - OUT: deploy-ecs-multi-env-image

  ######################################
  # Two parallel environments
  ######################################

  - name: deploy-ecs-multi-env-manifest-1
    type: manifest
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-image

  - name: deploy-ecs-multi-env-bluedeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-blueparams
      - IN: deploy-ecs-multi-env-manifest-1
        switch: off
      - IN: deploy-ecs-multi-env-maincluster

  - name: deploy-ecs-multi-env-greendeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-greenparams
      - IN: deploy-ecs-multi-env-manifest-1
        switch: off
      - IN: deploy-ecs-multi-env-maincluster


  ########################################
  # Two serial environments
  ########################################

  - name: deploy-ecs-multi-env-manifest-2
    type: manifest
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-commonparams
      - IN: deploy-ecs-multi-env-image

  - name: deploy-ecs-multi-env-betadeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-betaopts
      - IN: deploy-ecs-multi-env-betaparams
      - IN: deploy-ecs-multi-env-manifest-2
      - IN: deploy-ecs-multi-env-betacluster

  - name: deploy-ecs-multi-env-proddeploy
    type: deploy
    flags:
      - deploy-ecs-multi-env
    steps:
      - IN: deploy-ecs-multi-env-prodopts
        switch: off
      - IN: deploy-ecs-multi-env-prodparams
        switch: off
      - IN: deploy-ecs-multi-env-betadeploy
        switch: off
      - IN: deploy-ecs-multi-env-prodcluster
        switch: off
